.github/actions/upload-maven-artifacts/action.yml
.github/workflows/configuration-build-test.yml
countries/iraq/pom.xml
sites/mosul/pom.xml

this ensures that 
- any change in distro directory will cause a new release of Mosul and Iraq since they are children-
- any change in iraq directory will cause a new release of Mosul its a children
- any change in Mosul directory will only cause a release Mosul
- Artifact uploaded in with `upload-artifact` are zipped twice hence the installation script doesn't recursively unzip the file like the desktop unarchiver app would do.  see https://github.com/actions/upload-artifact/issues/39
cc @michaelbontyes @pirupius

Separate release pipeline and prevent GitHub artifact upload from zipping the artifact twice

---

distro/configs/openmrs/frontend_assembly/reference-application-spa-assemble-config.json
distro/pom.xml

this add the following:
- add ability for MSF to specify the OpenMRS docker image to use, preferably, qa 
- Add support for specifying the OpenMRS-core version to use, preferably, latest
- Point the MSF frontend configuration to use OpnMRS' test3 server
Persisting bugs probably inherited from Ozone:  https://msf-ocg.atlassian.net/browse/LIME2-282
cc @pirupius

LIME2-277: Migrate MSF-LIME ozone implementations to use the latest stable OpenMRS releases

---

.github/workflows/build-all.yml
.github/workflows/configuration-build-test.yml
distro/configs/openfn/azure.openfn.env
distro/configs/openfn/local.openfn.env
distro/pom.xml
scripts/docker-compose-openfn.yml

This PR simplifies running OpenFn on Azure and Local in the following ways.
- Adds 2 maven profile for adding the corresponding openfn env file to the artifact at compile time.
- Enables the local profile as default hence `/scripts/mvnw clean package` will always use local and in CI `/scripts/mvnw clean package -Pazure` will build using azure profile

Simplify running OpenFn on local and azure

---

distro/pom.xml

Ozone uses `Copy local resources` command to copy all contents of `*/config` to `*/target/***/distro/config` after compilation.
For some unknown reason, inheriting the same command with modification about the destination directory ie  from `*/config/openfn` to `*/target/***/distro/config/openfn` results in the build  ignoring the `frontend_config` directory hence not appending the logos and frontend configuration files
Kept command directories constant and changed the `<configuration>` of the command

(fix) Inherit ozone's 'Copy local resources' command without loosing files frontend Files

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F05-MH_Closure.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F06-MH-PHQ-9.json

1. Follow-up session: the 'Appointments' workspace should be hidden if 'No'
remains visible even when hide is hard coded to true hence needs community contribution 
```
{
"label": "Appointments",
"required": false,
"id": "appointmentsWorkspaceLauncher",
"questionOptions": {
"rendering": "workspace-launcher",
"buttonLabel": "Set the next appointment date",
"workspaceName": "appointments-form-workspace"
},
"hide": {
"hideWhenExpression": "true"
}
},
```
2.  Tooltip text partially hidden
This happens only hen the label has few characters ie short.
**Solution**:
- give a position to the tooltip, ie allow the tooltip to be displayed on the right in case the label is short
- add styling to the tooltip to span in only the visible space.

MH forms fine-tuning

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/Nutrition-Feeding_form.json

This PR adds a date validation to prevent duplicate encounter dates for nutrition feeding encounters

(fix) LIME2-379 Add duplicate date validation for nutrition encounters

---

README.md
distro/configs/traefik/config/tls.yml
distro/configs/traefik/config/traefik.yml
distro/pom.xml
scripts/docker-compose-openfn.yml
scripts/docker-compose-traefik.yml
scripts/msf-urls-template.csv
scripts/msf_utils.sh
scripts/run_msf_addons.sh
scripts/secrets/azure.msf.env
scripts/secrets/local.msf.env
sites/mosul/pom.xml

This PR adds ability to run a openMRS and OpenFn via a secure protocol.  read more [here](https://github.com/MSF-OCG/LIME-EMR/pull/55/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R90-R103)
The image below shows the urls when running with traefik enabled

LIME2-417: Enable ssl using Traefik and Let's Encrypt

---

README.md
distro/pom.xml
scripts/docker-compose-traefik.yml
scripts/msf_utils.sh
scripts/secrets/azure.msf.env
scripts/secrets/local.msf.env
sites/mosul/pom.xml

This PR migrates LIME to uses;
- [Release 1.0.0-alpha.11](https://github.com/ozone-his/ozone/releases/tag/1.0.0-alpha.11):  latest stable version of ozone his
- [RefApp-3.2.0-rc.3](https://hub.docker.com/layers/openmrs/openmrs-reference-application-3-frontend/3.2.0-rc.3/images/sha256-db27f69d29545598b24e55e604a6274bbcee2e4806b4eef85deeaf99e7c82e07?context=explore): The latest OpenMRS RefApp docker images
With traefik enabled, proxy remains running on port 80 hence OpenMRS remains accessible at `localhost/openmrs/spa` like shown in the image below.
https://msf-ocg.atlassian.net/browse/LIME2-420

LIME2-420 - Use ozone alpha and OpenMRS rc docker images

---

distro/pom.xml

This PR ensures that we override ozone to use LIME's `coreVersion` rather than that supplied to ozone by default

Supply LIME's frontend core version to ozone groovy file

---

distro/pom.xml

This PR:
- fixes permission issues in the stop-demo.sh and destroy-demo.sh scripts 
- ensures that stopping LIME should stop Traefik 
- ensures that destroying LIME should destory Traefik 
https://msf-ocg.atlassian.net/browse/LIME2-440
- `./stop-demo.sh`
- `./destroy-demo.sh`

Stop and destroy scripts should stop and destroy traefik servers correspondingly

---

distro/pom.xml
scripts/docker-compose-traefik.yml

Since different machine might be used ie one to compile and another to execute, its better to supply the env file using a relative path than an absolute path
https://msf-ocg.atlassian.net/browse/LIME2-426

Supply MSF env file using relative path

---

distro/pom.xml

Since ozone enforces the use of 3.0.0-beta.21 docker images in alpha 11, this PR ensures usage of 3.2.0-rc.3
https://msf-ocg.atlassian.net/browse/LIME2-441

fix LIME using 3.0.0-beta.21 docker images instead of 3.2.0-rc.3

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json

I didn't understand very well what Ludovic meant with the following reply
>Ludovic
>When the user select an answer in [Current symptoms or complaints 1], this answer belongs to one of the groups of problems: 'Psychosomatic related, 'Depression related'... or 'Other symptoms'. [Main category of symptoms] should be populated automatically by this category.
>
>Same for the precipitating factors. For example if the users selects ‘2.7 Domestic violence' in [Main past or precipitating events - 1], the question [Main category of precipitating event] should be populated automatically with 'Violence’.
I have just auto filled only `Main category of symptoms` and `Main category of precipitating event`
https://github.com/user-attachments/assets/cdb41ccd-0f92-4a6a-94a8-274ae41df36e …

Autofill the category of most important problems and precipitating factors

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json

This is meant to ensure that the MH Gap form;
- Matches latest metadata
- Form engine validator	
- MSF concepts only	
- All Workspaces work	
- All Skip logics work	
- All Calculations work	
- All Autofill work	
- All read-only fields working (ex. scores)	
- Arabic Translations	
- Submission works	
- All Values well saved and rendering in visits

fix MHGap-Baseline form

---

distro/configs/openfn/config.json
distro/pom.xml
scripts/run_msf_addons.sh
scripts/secrets/azure.msf.env
scripts/secrets/local.msf.env

This PR;
1. adds michael's email as the admin email
2. adds openmrs and dhis2 server urls
3. adds Madiro's azure url to cross origins

Refine OpenFn configuration

---

.github/workflows/build-all.yml
.github/workflows/configuration-build-test.yml

There are hard to debug reasons causing duplication while merging OpenFn workflows .  
This ensures that we use the same version of maven both locally while testing and in Github actions
Current behaviour in GitHub Actions
Expected behaviour

Modify GitHub Actions to use ./scripts/mvnw Maven wrapper

---

scripts/run_msf_addons.sh

Patch to `run_msf_addons.sh` to address issue Joshua was facing when testing WF2 `Get Encounters` step. This step uses `http` adaptor because we query the OMRS FHIR api, which requires `baseUrl` in the auth configuration... but the `omrs` adaptor (used in the other workflow steps) uses `instanceUrl`. In the immediate term, Josh addressed this by manually adding a new credential with `baseUrl` to the WF2 in his deployed instance. 
Merge this change if you want to ensure deployment of this `project.yaml` will work instantly, without manual intervention. 
Otherwise next week (estimated date: Jan 22), there will be an `openmrs` adaptor release with an enhancement that we can leverage and apply to the `project.yaml` file so that _all_ OMRS workflow steps can use the `openmrs` adaptor. **If no …

patch temporary fix to address WF2 error `unexpected relative url`

---

sites/mosul/configs/openfn/mosul-project.yaml

WF1 small change to add default gender "U" (unknown) when importing patients to OMRS if no patient.sex provided in DHIS2 source data. 
**Note:** TBD if we remove this later per MSF feedback; this is a temp fix to unblock testing.
UAT failure for WF1 where OMRS API returned error `Invalid Submission` if `patient.gender` was missing when trying to import `patient` data from DHIS2

wf1 add default gender to mosul-project.yaml

---

scripts/secrets/azure.msf.env
scripts/secrets/local.msf.env

This will increase `WORKER_MAX_RUN_DURATION_SECONDS` from `60` to `3600` and `WORKER_MAX_RUN_MEMORY_MB` to `1GB`
https://msf-ocg.atlassian.net/browse/LIME2-541

Increase workflow timeout to 1h and memory to 1GB

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json

Fixes the `hideWhenExpression` Logic for 'Specify if other fields' for 'Main diagnosis' and "Concomitant diagnosis"
https://github.com/user-attachments/assets/0b97a760-1aaf-43b9-9116-a9f48c9c374b
https://msf-ocg.atlassian.net/browse/LIME2-626

(fix) LIME2-626: Fix conditions for questions 'Main Diagnosis' and 'Concomitant diagnosis'

---

scripts/secrets/azure.msf.env

This aims to solve recursive loading of the OpenFn instance if the host is not among the cross origins
https://msf-ocg.atlassian.net/browse/LIME2-547

add FIWI host-name to  OpenFn cross origins environment variable

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

Adds the tooltip to the infant 1 name question
https://msf-ocg.atlassian.net/browse/LIME2-641

LIME2-641: Add tooltip to the infant 1 name question

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json

The condition was failing because the value was `undefined` hence added the check for the same.
https://msf-ocg.atlassian.net/browse/LIME2-627
------------
**Overview**
This PR fixes the `hideWhenExpression` for a specific field in the F29-MHPSS_Baseline_v2 form.  The updated logic now hides the field unless the `wasThePatientPrescribedPsychotropicMedication` field matches one of two specific UUIDs.
- Modified the `hideWhenExpression` to use `!==` (not equal to) and include two UUIDs, ensuring the field is visible only when the `wasThePatientPrescribedPsychotropicMedication` field matches either of these UUIDs.
Ready for deployment. This is a small, targeted fix with low risk.  The change directly addresses the reported issue with …

(fix) Fix the hideWhenExpression 

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json

Updates to history of mental disorder section to add new questions from metadata
https://msf-ocg.atlassian.net/browse/LIME2-616
------------
**Overview**
This PR adds a question about previous mental disorder diagnosis to the MHPSS Baseline form.  It includes a yes/no question and conditional logic to show further questions about the specific diagnosis only if the patient answers "yes."
- Added a new question "Does the patient have a previous mental disorder diagnosis?" to the "History of Mental Disorder" section.
- Added conditional logic to display subsequent diagnosis-related questions only when the patient answers "yes" to the new question.
- Expanded the list of possible diagnoses in the "whatWasTheDiagnosis" question.
Ready …

LIME2-616 MHPSS Baseline - question added in History of Mental Disorder section

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

Updates PNC form to;
- Updates normal and abnormal concepts
- Updates rendering for `passing urine or stool`
https://msf-ocg.atlassian.net/browse/LIME2-640
------------
**Overview:**
This PR updates the PNC (Postnatal Care) form (F13-PNC.json) by replacing generic string values ("normal", "abnormal") with specific OpenMRS concept UUIDs for improved data consistency and interoperability.  This change affects several fields related to infant and mother's health status.
- Replaced string literals "normal" and "abnormal" with corresponding concept UUIDs (`d884d3dd-7649-4260-b139-2d740baf9767` and `7beb61a4-2665-4326-a666-5cb4bea7a6ae` respectively) in multiple locations within the form definition.
- Modified several question sections to use radio button …

LIME2-640 Update PNC form adding new concepts for abnormal and normal

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

As per the ticket, there were 3 sections in the page "Evaluation of the mother":
1. Evaluation of the mother
2. PHQ2
3. PHQ2 Scoring
All these sections are merged into the first section, the label for the questions in the 2 sections is renamed, and the translations are updated.
https://msf-ocg.atlassian.net/browse/LIME2-642
------------
**Overview**
This PR merges sections under the 'Evaluation of the mother' page within the F13-PNC form by updating labels and conditional logic.  It specifically focuses on updating the PHQ-2 scoring section and results viewer.
- Changed the label of the "scoring" section to include referral instructions for scores of 3 or more.
- Modified the conditional visibility expressions for "scoring" and "results viewer" …

LIME2-642: Merge sections under 'Evaluation of the mother' page

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

https://msf-ocg.atlassian.net/browse/LIME2-641
------------
**Overview:** This PR addresses two issues in the F13-PNC form: It changes the "Number of consultations" question from a number input to a radio button selection with options for 1st, 2nd, and 3rd or more consultations. It also adds a tooltip to the "Infant 1" question to clarify its usage in cases of multiple births.
- Modified the `numberOfPnConsultation` question to use radio buttons instead of a number input.
- Added a tooltip to the `infantName` question explaining its usage for twins and higher-order multiple births.
- Updated the `hideWhenExpression` for subsequent questions to use the concept UUID of the "1st consultation" radio button option (`428825e2-73ec-407e-9988-e9646f1d1f14`) …

Fix the `Number of consultations` questions and add tooltip to Infant 1 question

---

sites/mosul/configs/openfn/mosul-project.yaml

Replace util.throwError with new Error function supported in earlier versions of common adaptor, and version-lock the adaptors referenced in the [adaptors registry cache](https://github.com/MSF-OCG/LIME-EMR/blob/main/sites/mosul/configs/openfn/adaptor_registry_cache.json) (which supports offline use). 
- Version lock each step in workflow.json
- Replace util.throwError with new Error (supported by common@2.1.1)
- Cleanup error logs to include duplicate patient numbers only
- Rename `Alert Admin` to `Alert Admin of Duplicate TEIs` 
- https://github.com/OpenFn/msf-lime-mosul/issues/95
- [Slack thread](https://openfn.slack.com/archives/C085ZC39PHP/p1742310625557689)

Update mosul-project.yaml to version-lock cached adaptors

---

sites/mosul/configs/openfn/projectState.json

This updates the `projectState` as on https://app.openfn.org/profile/tokens
------------
**Overview**
This PR updates the `projectState.json` file for the `msf-lime-mosul` project, primarily modifying the workflow configurations. The changes include renaming a job, updating its code, and specifying the `@openfn/language-common` adaptor version.
- Renamed the "Alert-Admin" job to "Alert-Admin-of-Duplicate-TEIs".
- Updated the code for the renamed job to include more detailed error information, specifically logging duplicate patient numbers.
- Pinned the `@openfn/language-common` adaptor version to 2.1.1 for the updated job.
- Updated timestamps for the project and workflows.
Ready for deployment. The changes are specific and …

Update project state for the new project workflow

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/Nutrition-Feeding_form.json

Change in feeding form to update the feeding product names
https://msf-ocg.atlassian.net/browse/LIME2-619
------------
**Overview**
This PR corrects the name of a nutritional product within the `Nutrition-Feeding_form.json` file, changing "RUTF B100" to "RUTF BP100".  This addresses LIME2-619.
- Corrected the product name label from "RUTF B100" to "RUTF BP100" in the specified JSON configuration file.
Ready for deployment. This is a simple label change with low risk and no apparent negative impact.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/notification?tab=codeHealth">Notification settings</a>.</h6>

(fix) LIME2-619 change in feeding product name

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F30-MHPSS_Follow-up_v2.json

Adds skip logic to Main category of precipitating event to MHPSS FU v2
https://msf-ocg.atlassian.net/browse/LIME2-629
------------
**Overview**
This PR adds hide logic to the "Main Category of Event" field in the MHPSS Follow-up form (F30). The field will only be displayed if the patient has suffered new critical events since the last consultation.
- Added a `hide` property with a `hideWhenExpression` to the "Main Category of Event" field configuration in `F30-MHPSS_Follow-up_v2.json`.  This expression checks the value of the "didThePatientSufferNewCriticalEventsSinceTheLastConsultation" field.
Ready for deployment. This change effectively implements the desired conditional logic and improves form usability.
<h6>To turn off PR …

LIME2-629 MHPSS FU v2 Add hide logic to main category event

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F31-mhGAP_Baseline_v2.json

Adds missing logic for `last question` in MHGAP baseline MHOS 
https://msf-ocg.atlassian.net/browse/LIME2-673

LIME2-673 add missing skip logic to mhgap baseline mhos

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json

Remove updated tooltips in MHPSS baseline v2
https://msf-ocg.atlassian.net/browse/LIME2-674
------------
**Overview**
This PR removes tooltips from two questions in the MHPSS Baseline form (F29) within the Mosul site configuration.
- Removed the `questionInfo` field from two question objects in the `F29-MHPSS_Baseline_v2.json` file.  These tooltips specified that only trained professionals should establish the diagnosis.
Ready for deployment. This change simplifies the form and removes potentially redundant information, assuming the qualification requirement is enforced elsewhere.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/notification?tab=codeHealth">Notification settings</a>.</h6>

LIME2-674 mhpss baseline remove updated tooltips

---

scripts/docker-compose-openfn.yml
scripts/run_msf_addons.sh

This PR upgrades openfn versions to the latest available ones
------------
**Overview:**
This PR upgrades the OpenFN services, including Lightning and the worker, to newer versions (v2.11.0 and v1.13.0, respectively). It also updates the OpenFN CLI version used for pre-warming the worker cache to v1.11.4.
- Updated the Lightning image version in the docker-compose file from v2.10.10 to v2.11.0 for both the migrations and web services.
- Updated the worker image version from `latest` to v1.13.0.
- Updated the OpenFN CLI version used in the `run_msf_addons.sh` script from 1.10.2 to 1.11.4.
- Minor formatting changes in the `run_msf_addons.sh` script.
Stable for release. This PR involves straightforward version upgrades of existing …

upgrade openfn services

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F33-MHPSS_Closure_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F34-mhGAP_Closure_v2.json

Adds check to prevent setting future dates for closure date
------------
**Overview:** This PR updates the closure date validators for F33-MHPSS_Closure_v2 and F34-mhGAP_Closure_v2 forms to ensure the closure date is after the opening date and not in the future.  This addresses potential data integrity issues.
- Separated the date validation checks into two distinct validators for clarity and more specific error messages.
- Added a validator to prevent future closure dates.
- Updated the `F33-MHPSS_Closure_v2.json` and `F34-mhGAP_Closure_v2.json` configuration files.
Ready for deployment. This is a small, targeted change with a clear improvement to data validation.
<h6>To turn off PR summary, please visit <a …

Update the validators for the closure date on closure forms

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F30-MHPSS_Follow-up_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F31-mhGAP_Baseline_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F32-mhGAP_Follow-up_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F35-MH-PHQ-9_v2.json

- Resolves https://msf-ocg.atlassian.net/browse/LIME2-687
https://github.com/user-attachments/assets/ce383d6e-20b9-480f-a01a-5a4a494e93d5
------------
**Overview**
This PR corrects the `id` of a question related to appetite in several MHPSS and mhGAP forms.  The `id` is changed from `poorAppetiteOrOvereating` to `poorAppetiteOrOverEating` to maintain consistency.
- Updated the `id` field in five JSON files: `F29-MHPSS_Baseline_v2.json`, `F30-MHPSS_Follow-up_v2.json`, `F31-mhGAP_Baseline_v2.json`, `F32-mhGAP_Follow-up_v2.json`, and `F35-MH-PHQ-9_v2.json`.
Ready for deployment. This is a simple ID correction with low risk and improves consistency.
<h6>To turn …

(fix) LIME2-687 PHQ9 calculation question id

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F08-ITFC_Admission_form.json

- Closes https://msf-ocg.atlassian.net/browse/LIME2-693
------------
**Overview**
This PR fixes broken skip logic in the ITFC Admission form (F08) by correcting the IDs of several "If other, specify" obs fields and renaming Secondary diagnosis fields to be more descriptive.  This addresses LIME2-693.
- Renamed ambiguous IDs like `ifOtherSpecify` to more specific ones like `ifReferredByWhomOrFromWhere_ifOtherSpecify`, `whoIsTheHeadOfFamily_ifOtherSpecify`, `mainDiagnosisAtAdmission_ifOtherSpecify`, `diagnosisAtAdmissionSecondary1_ifOtherSpecify`, `diagnosisAtAdmissionSecondary2_ifOtherSpecify`, and `diagnosisAtAdmissionSecondary3_ifOtherSpecify`.
- Clarified the labels of …

(fix) LIME2-693 ITFC admission fix broken skip logic

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json

- Closes #LIME2-703
------------
**Overview**
This PR re-enables the laboratory dashboard link on the homepage dashboard for the MSF Mosul instance by removing it from the list of removed items in the frontend configuration.
- Removed `"laboratory-dashboard-link"` from the `"remove"` array within the `"homepage-dashboard-slot"` configuration.  This change effectively restores the visibility of the laboratory dashboard link.
Ready for deployment. This is a small, targeted change with low risk.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/notification?tab=codeHealth">Notification settings</a>.</h6>

LIME2-703 Re-enable laboratory dashboard

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json

Link to the ticket: https://msf-ocg.atlassian.net/browse/LIME2-691
Updates the order of answers for the question: "Secondary 3" and also updates the hide logic with correct UUID.
------------
**Overview:**
This PR updates the ITFC Discharge form configuration by modifying the `hideWhenExpression` for "Other" options and reorganizing/adding several disease options within the form's structure.  This aims to improve the form's logic and completeness.
- Changed `hideWhenExpression` from comparing against the label "other" to comparing against the concept UUID for "Other" for several fields.
- Reordered and added several disease options related to neonatal care, infections, and other conditions to provide a more comprehensive list. …

LIME2-691: Update the ITFC Discharge form answers

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F10-ATFC_form.json
sites/mosul/configs/openmrs/initializer_config/ampathformstranslations/F09-ITFC_Discharge_form_translations_ar.json
sites/mosul/configs/openmrs/initializer_config/ampathformstranslations/F09-ITFC_Discharge_form_translations_en.json
sites/mosul/configs/openmrs/initializer_config/ampathformstranslations/F10-ATFC_form_translations_ar.json
sites/mosul/configs/openmrs/initializer_config/ampathformstranslations/F10-ATFC_form_translations_en.json

This PR fixes the conditions for vaccination related questions' followup question (Was the last dose given at site?) which had the condition as `vaccination !== 'Unknown' || vaccination != 'Not vaccinated'`, which actually if understood correctly is true for any selection among (Dose 1, Not vaccinated, Unknown).  
https://github.com/user-attachments/assets/48f1089f-1c6c-40d9-be92-6e525aae2a08

LIME2-706: Fix hide expressions for vaccination questions in ITFC/ ATFC

---

scripts/docker-compose-openfn.yml
sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json

Fetch the admission datetime of the patient in the ITFC Discharge form.
Link to the ticket: https://msf-ocg.atlassian.net/browse/LIME2-385
https://github.com/user-attachments/assets/4d2bf76c-e6e2-4f6b-b480-4ce60cb02972
As shared in the Dev call, there seems to be an issue with the time field not getting populated. I'll work on the form engine lib to fix that, but it doesn't become a blocker for this ticket.
------------
**Overview**
This PR modifies the ITFC Discharge form to fetch the admission datetime from a previous observation instead of using the current datetime.  This addresses the need to record the actual admission time rather than the discharge time.
- Updated the `calculateExpression` for the admission datetime field in the ITFC Discharge …

LIME2-385: Fetch the admission datetime in the ITFC discharge form

---

scripts/docker-compose-openfn.yml
sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json

Link to the ticket: https://msf-ocg.atlassian.net/browse/LIME2-706
https://github.com/user-attachments/assets/1d0b72e7-0ea2-47a0-8ad4-c3a8bab40c91
------------
**Overview:** This PR reverts a previous change related to the validation of various vaccinations within the `F09-ITFC_Discharge_form`. It modifies the `hideWhenExpression` logic to consider `null` values and specific UUIDs. Additionally, it updates docker configurations, likely for platform compatibility.
- Modified the `hideWhenExpression` in the `F09-ITFC_Discharge_form` to handle `null` values and include an "or" condition for specific UUIDs related to vaccinations.
- Updated the `docker-compose-openfn.yml` file, changing the platform from `linux/x86_64/v8` to `linux/x86_64` for both …

LIME2-706: Revert the check for various vaccinations

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/Nutrition-Feeding_form.json

- Related to #LIME2-676
------------
**Overview**
This PR adds read-only permissions to specific nutrition-related fields within the `Nutrition-Feeding_form`.  Users without the "Manage Nutrition" privilege will be unable to edit these fields.
- Added `readonly` property to "Feeding Phase," "Feeding Product," "Quantity," and "Number of meals" fields, conditionally enabled based on the "Manage Nutrition" privilege.
Ready for deployment. This simple change effectively restricts unauthorized modification of key nutrition fields.
|---|---|
| New Work | 4 (100%) |
| Total Changes | 4 |
<h6>To turn off PR summary, please visit <a …

LIME2-676 Add readonly nutrition permissions to prescription fields

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

Removes the Test: [C-reactive Protein](https://app.openconceptlab.org/#/orgs/MSF/sources/MSF/concepts/4000/) from the existing Dev and UAT Database.
------------
**Overview**
This PR removes the C-reactive Protein test from the Tests Orderability concept set within the OpenMRS configuration for the Mosul site.  This change is tracked by LIME2-713.
- A new changeset `remove_crp_from_tests_orderability` is added to the `liquibase.xml` file. This changeset executes an SQL DELETE statement to remove the association between the C-reactive Protein test concept and the Tests Orderability concept set.
Ready for deployment. This is a small, targeted change with a clear purpose.
| Category    | Lines Changed | …

LIME2-713: Add `changeSet` to remove test from tests orderability set

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json

I’ve made the following updates:
1. I’ve updated the `id` for all the ‘If other, specify’ questions and linked them to the related question.
2. If the parent’s hide expressions for the ‘If other, specify’ questions are related to a question, the hide expression should also include the parent’s hide equation. Otherwise, if the user fills in the necessary options for the ‘If other, specify’ question and then changes the grandparent’s option, the ‘If other, specify’ question should still be visible, as demonstrated in the video below.
https://github.com/user-attachments/assets/98141487-0453-49f4-940a-0966777ffd25
- Closes #LIME2-729

(fix) LIME2-729: Fix the hide logic for all 'If other, specify' questions

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

- Closes #LIME2-733
------------
**Overview:**
This PR fixes the rendering of the Anaemia question in the F13-PNC form by changing the question type from "markdown" to "obs" and using a radio button rendering with predefined answer options. This addresses LIME2-733.
- Changed the `type` of the "anaemia" question from `markdown` to `obs`.
- Changed the `rendering` from `markdown` to `radio` and added a `concept` for structured data capture.
- Removed the `value` field which was redundant with the new rendering approach.
- Included explicit answer options ("No", "Yes", "Unknown") linked to coded concepts.
Ready for deployment. This fix improves data quality …

(fix) LIME2-733 PNC - Update Anaemia question rendering from markdown to radio

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json

- Related to #LIME2-728
------------
**Overview**
This PR addresses duplicate question IDs in the `F09-ITFC_Discharge_form.json` file by renaming fields related to weight, height, WHZ, and MUAC at admission and discharge. It also modifies skip logic expressions to use `isEmpty()` instead of direct null checks, improving form behavior.
- Renamed admission and discharge fields for weight, height, WHZ, and MUAC to ensure unique IDs.
- Updated skip logic expressions to use `isEmpty()` for more robust handling of null or empty values.
Ready for deployment. This PR improves data integrity and form functionality with straightforward changes.
| Category | Lines …

(fix) LIME2-728 Fixes to duplicate question ids and updates to skip logic

---

distro/pom.xml
scripts/docker-compose-openfn.yml
scripts/secrets/azure.msf.env
scripts/secrets/local.msf.env
sites/mosul/pom.xml

- Closes [#LIME2-780](https://msf-ocg.atlassian.net/browse/LIME2-780)
------------
**Overview:**
This PR removes the concatenation of environment variables from the `pom.xml` build process and updates the docker compose files to use a single `concatenated.env` file.  This simplifies environment variable management.
- Removed the Maven execution block responsible for concatenating environment files during the build.
- Updated the `docker-compose-openfn.yml` file to point to `concatenated.env`.
- Added Ozone Configuration sections to `azure.msf.env` and `local.msf.env`.
- Removed redundant regex replacement in `sites/mosul/pom.xml`.
Ready for deployment. …

(fix) Add support for using concatenated env file to load msf environment variables 

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

- Closes #LIME2-123
------------
**Overview:**
This PR fixes an issue where Liquibase changesets were failing on a fresh OpenMRS installation. The changes ensure the `provider` table insert and a report design update only execute when the necessary tables exist.
- Removed a hardcoded `provider_id` value from the `provider` table insert to rely on auto-increment functionality.
- Added preconditions to check for the existence of `reporting_report_design` and `provider` tables before applying subsequent changesets. This prevents errors on fresh installations where these tables might not yet exist.
Ready for deployment. This PR …

LIME2-883: Fix liquibase changesets to run correctly on a fresh start

---

scripts/docker-compose-openfn.yml
scripts/run_msf_addons.sh
scripts/secrets/azure.msf.env
scripts/secrets/local.msf.env

- Closes #[LIME2-904](https://msf-ocg.atlassian.net/browse/LIME2-904)
- Relates to #228 
------------
**Overview:** This PR dedicates a PostgreSQL container specifically for OpenFn, improving resource management and isolation. It updates the docker-compose file, environment variables, and scripts to use the new container.  The PR also updates the OpenFn Lightning and worker images to newer versions.
- Creates a dedicated `openfn-postgresql` service in `docker-compose-openfn.yml`.
- Updates environment variables and scripts to reference the new container name.
- Adds health checks for the PostgreSQL container.
- Upgrades `openfn/lightning` to v2.14.0 and `openfn/ws-worker` to …

(feat) Dedicate OpenFn to use its own PostgreSQL container

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F43-ER_exit_form.json

https://github.com/user-attachments/assets/cd7957dc-16fe-40f1-82ff-0fdf96938802
- Closes #LIME2-123
------------
**Overview:** This PR fixes the skip logic in the ER Exit form by adding an additional condition to the `hideWhenExpression` for several fields.  This ensures fields are hidden based on the 'outcome' field value in addition to the previously existing conditions.
- Modified the `hideWhenExpression` for "referralPlace", "deathCause", and "specifyTheUnit" fields in the ER Exit form configuration.  The updated logic now checks the `outcome` field value before hiding these fields.
- Removed an empty "None" section.
Ready for …

(fix) LIME2-920 Fix the skip logic in the ER Exit form

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F23-Neonatal_admission_form.json

- Closes #LIME2-939
------------
**Overview:** This PR replaces the workspace launcher with a markdown display for the "Prescribe with the feeding form if necessary" field in the Neonatal Admission form.  This change simplifies the user interface and provides a clearer prompt.
- Changed the field type from "workspace-launcher" to "markdown."
- Removed workspace-related configurations (`buttonLabel`, `workspaceName`).
- Added a conditional hiding rule based on the `feedingMethod` value. The markdown element will only be displayed if the feeding method is neither breast milk nor expressed breast milk.
Ready for deployment. This change simplifies the UI and …

LIME2-939 replace workspace with markdown on neonatal admission

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F21-Anesthesia_transfer_form.json

- Closes #LIME2-944
------------
**Overview:** This PR moves the workspace question "Order medications" within the Anesthesia Transfer Form configuration to replace a markdown question with the same instructions. This streamlines the form by directly integrating the workspace launcher instead of presenting redundant information.
- Removed the markdown question "Check in 'Medications'..." and its associated configuration.
- Modified the label of the "orderMedications" workspace question to include the instructions previously displayed in the markdown question.
Ready for deployment. This change simplifies the user experience and removes redundancy.
| …

LIME2-944: Move the workspace question to the markdown question

---

sites/mosul/configs/openfn/projectState.json

This PR removes parameters in `projectState.json` that was causing deploy to fail with the following error
```bash
[CLI] ✘ Failed to deploy project msf-lime-test:
{
"errors": {
"base": [
"extraneous parameters: color, env, parent_id, version_history"
]
}
}
[ERROR] Unable to deploy OpenFn workflow.
```

Remove extraneous parameters in `projectState.json`
