distro/configs/openmrs/frontend_config/msf-frontend-config.json
distro/configs/openmrs/initializer_config/autogenerationoptions/autogenerationoptions.csv
distro/configs/openmrs/initializer_config/idgen/idgen_sequential.csv
distro/configs/openmrs/initializer_config/patientidentifiertypes/patientidentifiertypes.csv
distro/pom.xml

Add support for MSF ID generation on patient registration

---

distro/configs/openmrs/initializer_config/patientidentifiertypes/patientidentifiertypes.csv
sites/mosul/configs/openmrs/initializer_config/idgen/idgen_sequential.csv
sites/mosul/pom.xml

this is a follow up of https://github.com/MSF-OCG/LIME-EMR/pull/2  and https://github.com/Madiro-org/MSF-OCG-patient-identifier-generator/commit/916549115a5b1d358e2b2c7ea50467a02855d160
Documentation is a WIP 
Ready to test on Mosul

Update support for adding an MSF ID generation on patient registration

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json
sites/mosul/configs/openmrs/initializer_config/personattributetypes/personattributetypes_core-demo.csv

Added;
- Family Name 2
- Family Name 3
As personal attributes

Add optional additional family name fields (Works fine)

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

Adds Liquibase migrations to update person_attribute value after switch from string to concept

LIME2-308 emergency contact relationship migration from string to concept

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json

Hide Patient orders and attachments esm apps from the patient chart 

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

This fixes issue with missing provider data for users. It also resolves issue with order basket and visit notes
https://github.com/MSF-OCG/LIME-EMR/assets/15266028/2050ef9a-9390-4455-a5ce-7bb254a6f8a3

LIME2-322 make default users providers

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json

Registration Officer
Nurse, Doctor and other users

(fix) LIME2-332 fix privileges on patient chart action menu

---

README.md
distro/configs/openfn/config.json
distro/configs/openfn/openfn.env
distro/configs/openfn/project.yaml
distro/pom.xml
scripts/data/postgresql/create_openfn_db.sh
scripts/docker-compose-files.txt
scripts/docker-compose-openfn.yml
scripts/merge-openfn-yaml.groovy
sites/mosul/configs/openfn/mosul-project.yaml
sites/mosul/pom.xml

see documentation added to the Readme
https://github.com/user-attachments/assets/0e409489-a249-4ee6-8928-6077901355cf

Setup support for running  OpenFn web UI

---

scripts/docker-compose-openfn.yml

This simply fixes the typo in OpenFn's directory environment file

Fix typo in Openfn's configuration directory path variable

---

distro/configs/openfn/azure.openfn.env
distro/configs/openfn/local.openfn.env
distro/pom.xml
scripts/run_msf_addons.sh

**OpenMRS username:** admin
**OpenMRS password:** Admin123
**DHIS2 username:** admin
**DHIS2 password:** Admin123

Create MSF OpenFn user by default on start-up

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F07-ITFC_Admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F08-ITFC_discharge_form.json

1. [Admission type]: modification done in metadata → option ‘Patient referred’ removed  →  ✅
3. [Spontaneous admission]: modification done in metadata → moved after [Admission type] →  ✅
5. Patient referred by - [If other specify]: issue → skip logic not working →  ✅
7. [Please check in "Vitals & Biometrics" for "…]: issue → workspace missing →  ✅
9. [Prescription]: issue → workspaces missing →  ✅
1. [By whom/from where] - If other specify: modification done in metadata → skip logic changed from “Hide question if [Admission type] !== 'Patient referred'“ to “Hide question if [Spontaneous admission] !== 'No'“ →  ✅
2. [Discharge date]: modification done in metadata→ fill with current date →  ✅
3. Section [Condition at discharge]: issue → questions missing: Weight at discharge (in Kg) …

(fix) Tune  ITFC forms

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F07-ITFC_Admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F08-ITFC_discharge_form.json

As most requirements for the ITFC forms are working fine, while further testing,  i found out that some skip-logic and feeding form workspace wasn't working well.  
This fixes all the above.

(fix) follow-up tuning ITFC-forms: Skip-logic and workspaces

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F06-mhGAP_Closure.json
sites/mosul/configs/openmrs/initializer_config/ampathformstranslations/F06-mhGAP Closure_translation_ar.json

This PR adds:
- a new mhGAP closure form
- Change 'Clinical diagnosis' from multicheck to select
- Replace ‘Patient experienced an act of aggression or violence - What type(s) of violence?’ multicheckbox to 3 questions:

MH forms update (mhGAP and MHPSS forms)

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json

https://github.com/user-attachments/assets/42bca4fe-44ca-4ebd-83aa-14e6e543c6ac

Autofill Clinical diagnosis with previous form values

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json

https://github.com/user-attachments/assets/6ced2069-7436-4d3b-9e8b-8a1e45b75907

Autofill Sex with previous form values

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json

Updates MHOS and PHQ-9 Scores, shortens question id fields

LIME2-421 Update logic for MHOS and PHQ-9 scores

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/Nutrition-Feeding_form.json

Enforce date validation for enter mode only. Skip for edit mode
https://msf-ocg.atlassian.net/browse/LIME2-427

LIME2-427 Adds extra nutrition date validation param

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

Removes duplicate inconnu (aka unknown) concepts
https://msf-ocg.atlassian.net/browse/LIME2-398

LIME2-398 Remove conflicting unkown aka inconnu concept

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json

This PR handles the new set of questions for MHOS score, for which the skip logic depends on the patient' age (there are questions for patients below 15, and other questions for 15 and above)
https://msf-ocg.atlassian.net/browse/LIME2-413

Update MHOS score questions and autofills

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F08-ITFC_discharge_form.json

(fix) LIME2-442 MHOS and PHQ9 score calculation

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json

There was a concept mixup for some answers

(fix) LIME2-444 Fix skip logic for main current symptoms

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F01-MHPSS_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F02-MHPSS_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F03-mhGAP_Baseline.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F05-MHPSS_Closure.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F06-MH-PHQ-9.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F06-mhGAP_Closure.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F07-ITFC_Admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F08-ITFC_discharge_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/Nutrition-Feeding_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/Test-Privilege-based-fields.json

(forms) Remove answer labels

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F04-mhGAP_Follow-up.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F06-mhGAP_Closure.json
sites/mosul/configs/openmrs/initializer_config/globalproperties/skip_location_datafilters.xml

This PR ensures that only Mental Health users can access Mental Health encounters
https://github.com/user-attachments/assets/2886031e-73a5-4992-8de8-111fc05d479d

Hide MH encounters and forms from other non-MH users

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json

https://msf-ocg.atlassian.net/browse/LIME2-453

add Arabic translation for configuring identifiers

---

README.md

We now no-longer need to install OpenFn CLI and deploying using a local machine.  This PR aims at updating that information

Update Docs to reflect the latest changes in OpenFn

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json
sites/mosul/configs/openmrs/initializer_config/personattributetypes/mosul_personattributetypes.csv

This PR enhances search filters by including registration fields with string format 
https://msf-ocg.atlassian.net/browse/LIME2-214
https://github.com/user-attachments/assets/bf1cae30-10d1-45b7-abbe-512acb3d2f15
https://github.com/user-attachments/assets/7959120e-a1a0-4f0f-9cef-865ee7e2d733

Add string-formatted registration fields to search filters

---

README.md

This PR updates the README.md with instructions for configuring the `~/.m2/settings.xml`.

(docs) Add instructions for Maven Configuration

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F11-Family_Planning_Assessment.json

https://github.com/user-attachments/assets/5bd08d23-43c4-45ff-8c4c-dd62d9f68b42
https://msf-ocg.atlassian.net/browse/LIME2-631

(fix) LIME2-631: Add steps for numeric fields in Family planning assessment

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json

Tested on Form Builder
https://github.com/user-attachments/assets/d7b55a95-ff2d-4074-af2e-33d7afbd2807
https://msf-ocg.atlassian.net/browse/LIME2-627

(feat) LIME2-627: Update the `hideWhenExpression` for 'If yes, enter details in "Medications"

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F31-mhGAP_Baseline_v2.json

mhGAP Baseline v2 - rename and change order of questions/sections
https://msf-ocg.atlassian.net/browse/LIME2-634

LIME2-634 mhGAP Baseline v2 - rename and change order of questions/sections

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F10-ATFC_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F11-Family_Planning_Assessment.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F30-MHPSS_Follow-up_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F31-mhGAP_Baseline_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F32-mhGAP_Follow-up_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F33-MHPSS_Closure_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F34-mhGAP_Closure_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/Nutrition-Feeding_form.json

https://msf-ocg.atlassian.net/browse/LIME2-667
------------
**Overview**
This PR updates several forms, primarily correcting label spacing and trailing spaces, and aligning concept datatypes for consistency and improved data quality.  It also modifies a few `hideWhenExpression` conditions and question IDs for better logic and readability.
- Removed trailing spaces and standardized spacing in labels across multiple forms (F10, F11, F13, F29, F30, F31, F32, F33, F34, Nutrition-Feeding_form).
- Updated concept datatypes and corrected concept UUIDs in F29, F30, F31, F32 to ensure data integrity.
- Modified `hideWhenExpression` conditions in F13, F29, F30, F31, F32 to use concept UUIDs instead of labels for improved reliability.
- Changed question IDs in …

LIME2-667 Form updates and concepts datatype changes

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F31-mhGAP_Baseline_v2.json

Switched the skip logic on the "Yes" instead of the "No" for follow-up required in mhGAP baseline v2:
https://github.com/user-attachments/assets/2fbdc5d4-0db8-4a24-bb8e-6ff6456c1889
https://msf-ocg.atlassian.net/browse/LIME2-567

(Fix) LIME2-567: mhGAP v2 - switch of Follow -up skip logic

---

distro/configs/openmrs/frontend_assembly/spa-assemble-config.json

- Closes  https://msf-ocg.atlassian.net/browse/LIME2-612
- Related to https://msf-ocg.atlassian.net/browse/LIME2-496 and https://msf-ocg.atlassian.net/browse/LIME2-629

(chore) Upgrade form engine and form builder apps

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F09-ITFC_Discharge_form.json

- Closes https://msf-ocg.atlassian.net/browse/LIME2-696
------------
**Overview**
This PR fixes a bug in the ITFC Discharge form where the "Number of days" field was incorrectly linked to the same obs concept ID for both "Intensive Care Unit" and "Isolation Unit" sections.
- Renamed the `numberOfDays` obs field ID to `numberOfDaysInIntensiveCare` within the "Intensive Care Unit" section.
- Renamed the `numberOfDays` obs field ID to `numberOfDaysInIsolationUnit` within the "Isolation Unit" section.  This ensures that each section correctly captures the number of days spent in the respective units.
Ready for deployment. This straightforward fix corrects a data …

(fix) LIME2-696 ITFC discharge skip logic for stay in isolation unit

---

distro/configs/openmrs/initializer_config/globalproperties/fhir-properties.xml

- Closes #LIME2-738
------------
**Overview**
This PR adds a new global property `fhir2.administeringEncounterRoleUuid` to the FHIR properties file (`fhir-properties.xml`). This property likely configures the encounter role associated with immunization administration within the OpenMRS system.
- Added a new global property `fhir2.administeringEncounterRoleUuid` with the UUID `240b26f9-dd88-4172-823d-4a8bfeb7841f` to the `fhir-properties.xml` file.
Ready for deployment. This is a simple configuration change with minimal risk.  Ensure the UUID `240b26f9-dd88-4172-823d-4a8bfeb7841f` corresponds to the correct encounter role in OpenMRS.
| Category    | Lines …

(fix) LIME2-738 Add immunization encounter configuration

---

sites/mosul/configs/openmrs/frontend_config/msf-mosul-frontend-config.json
sites/mosul/configs/openmrs/initializer_config/personattributetypes/mosul_personattributetypes.csv
sites/mosul/configs/openmrs/initializer_config/personattributetypes/personattributetypes_core-demo.csv

- Closes #LIME2-738
------------
**Overview:** This PR fixes the "Unknown Patient Name" attribute configuration by replacing the existing UUID (`7de00b51-3342-4191-92e8-ca4eb4ed8085`) with a new one (`8b56eac7-5c76-4b9c-8c6f-1deab8d3fc47`) across multiple configuration files. This change allows proper registration of unknown patients.
- Replaced the old `attributeTypeUuid` for "Unknown Patient Name" with the new UUID in `msf-mosul-frontend-config.json`.
- Updated `mosul_personattributetypes.csv` and `personattributetypes_core-demo.csv` to reflect the new UUID and attribute name ("Unknown patient").
Ready for deployment. This is a straightforward …

(fix) LIME2-738 Ability to register unknown patient

---

distro/pom.xml

The update in RESTWS allows us with the latest change in the `Encounter` API which now supports sorting by date and filtering by Encounter type.
https://github.com/user-attachments/assets/30d5c02b-c06c-4763-82ff-da6dc7c9d362
- Closes [LIME2-742](https://msf-ocg.atlassian.net/browse/LIME2-742)
------------
**Overview:**
This PR updates the OpenMRS platform version to 2.7.4 and the REST Web Services version to 2.49.0.  These updates are likely necessary for compatibility, security updates, or to leverage new features in these dependencies.
- Updated the `pom.xml` to include the new OpenMRS and REST Web Services versions.
- Added explicit dependencies for `openmrs-webapp` and …

LIME2-742: Update the Platform and RESTWS version

---

docs/README.md
sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

(fix) LIME2-732 update last delivery problems skip logic for multiselect

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

(fix) LIME2-736 PNC referral reason skip logic

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

(fix) LIME2-735 PNC circumference skip logic conflict

---

scripts/apply-overrides.groovy
sites/mosul/configs/openmrs/initializer_config/jsonkeyvalues/patientIdPreportConfig.json
sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

- Closes #[LIME2-753
](https://msf-ocg.atlassian.net/browse/LIME2-753)

(fix) Arabic disjointed letters on stickers

---

sites/mosul/configs/openmrs/initializer_config/drugs/drugs.csv

- Closes #LIME2-123
------------
**Overview:** This PR removes two duplicate drug entries from the `drugs.csv` file used for OpenMRS initialization in the Mosul site configuration.  This cleanup improves data integrity and prevents potential conflicts.
- Removed duplicate entries for "MONTELUKAST, 5mg, chewable tab." and "IMMUNOGL. SNAKE ANTIVENOM, Africa (SAIMR), 10ml, amp." from the `drugs.csv` file.
Ready for deployment. This is a simple, low-risk change that directly addresses data duplication.
|----------|---------------|
| Churn    | 2 (100%)     |
| Total Changes | 2           |
<h6>To turn off PR …

LIME2-298: Remove duplicate drugs from the sheet

---

sites/mosul/configs/openfn/projectState.json
sites/mosul/configs/openfn/version.txt

- Support for custom logic for forms F29-MHPSS Baseline v2, F30-MHPSS Follow-up v2, F31-mhGAP Baseline v2, F32-mhGAP Follow-up v2, F33-MHPSS Closure v2, F34-mhGAP Closure v2
- WF1 and WF2 are using  `LIME EMR - Iraq Metadata - Release 1 - v2025-06-23.xlsx` metadata file
- F29-MHPSS Baseline v2, F30-MHPSS Follow-up v2, F31-mhGAP Baseline v2, F32-mhGAP Follow-up v2, F33-MHPSS Closure v2, F34-mhGAP Closure v2, F00-Registration, F01-MHPSS Baseline, F02-MHPSS Follow-up, F03-mhGAP Baseline, F04-mhGAP Follow-up, F05-MHPSS Closure and F06-mhGAP Closure
- For testing the custom logic introduced in these forms, run through scenarios 9 -14 from this [test suite](https://docs.google.com/spreadsheets/d/13yjqiejKFf6HlNCvgfgaKNi9Gffhq22RUTwXKUPR36k/edit?gid=1426424864#gid=1426424864).
**Yaml version: …

Feature - Custom mapping logic for f29, f30, f31, f32, f33, 34

---

docs/CHANGE_LOG.md

------------
**Overview:** This PR updates the changelog for Sprint 29, documenting features, improvements, bug fixes, housekeeping tasks, and experimental changes released on July 11, 2025.  It provides a comprehensive overview of the updates for this release.
- Added a new release entry for July 11, 2025, detailing various changes categorized as Features & Improvements, Bug Fixes, House Keeping, and Experimental.
- Included Jira ticket links for each change to provide traceability and context.
- Minor formatting adjustments were made to previous changelog entries.
Ready for deployment. This PR effectively documents the changes for the sprint, improving …

(chore) Update changelog for Sprint 29

---

sites/mosul/configs/openfn/version.txt

Changes included in this version:
- Edits on WF2 to enable dynamic implementation of syncing latest encounters for a patient for baseline and closure forms and syncing latest forms for follow up forms
- Update WF1 and WF2 to use latest metadata file: "LIME EMR - Iraq Metadata - Release 1 - v2025-07-14"
- F29-MHPSS Baseline v2, F30-MHPSS Follow-up v2, F31-mhGAP Baseline v2, F32-mhGAP Follow-up v2, F33-MHPSS Closure v2, F34-mhGAP Closure v2, F00-Registration
https://github.com/OpenFn/msf-lime-mosul/issues/124
For testing the logic introduced in this PR, run through scenarios 14 and 15 from this [test suite](https://docs.google.com/spreadsheets/d/13yjqiejKFf6HlNCvgfgaKNi9Gffhq22RUTwXKUPR36k/edit?gid=1426424864#gid=1426424864).
**Yaml version: v1.2.1**

Fix for Syncing latest encounters vs all encounters

---

sites/mosul/configs/openmrs/initializer_config/locations/mosul_locations.csv

Resolves the following issue: 
- Closes #LIME2-896
------------
**Overview:** This PR removes two location attributes, `Attribute|9eca4f4e-707f-4bb8-8289-2f9b6e93803c` and `Attribute|Last Audit Date`, from the `mosul_locations.csv` file.  These attributes were not loading correctly after a platform upgrade.
- Removed two unused attributes from the location configuration file. This simplifies the configuration and resolves the loading issue.
Ready for deployment. This change is low-risk and directly addresses the reported issue.
|---|---|
| Rework | 3 (100%) |
| Total Changes | 3 |
<h6>To turn off PR …

LIME2-896: Remove the locations' attributes, which are not loading after platform upgrade

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

- Closes #LIME2-123
------------
**Overview:** This PR updates the Liquibase changeset ID `add_admin_provider-202407101630` to `add_admin_provider-20250808` in the `liquibase.xml` file to likely resolve a checksum-based issue.  This change allows Liquibase to reapply the changeset.
- Modified the changeset ID in `liquibase.xml` from `add_admin_provider-202407101630` to `add_admin_provider-20250808`.
Ready for deployment. This simple ID change effectively addresses the checksum issue without introducing any new logic or dependencies.
|---|---|
| Rework | 1 (100%) |
| Total Changes | 1 |
<h6>To turn off PR …

Update liquibase changeset ID for skipping checksum based issue

---

distro/configs/openmrs/initializer_config/globalproperties/globalproperties-person.xml

- Closes #LIME2-898
------------
**Overview:** This PR adds a global property override for `person.searchMaxResults` in the OpenMRS initializer configuration. This change allows customizing the maximum number of results returned in person searches.
- Added `globalproperties-person.xml` to the `initializer_config` directory.
- Set the `person.searchMaxResults` property to `2000`.
Ready for deployment. This simple configuration change effectively manages the search result limit.
| --------- | ------------- |
| New Work | 8 (100%)     |
| Total Changes | 8         |
<h6>To turn off PR summary, please visit <a …

LIME2-898 Adds globalproperties-person override for searchMaxResults

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F20-Recovery_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F21-Anesthesia_transfer_form.json

- Closes #LIME2-931
------------
**Overview:** This PR fixes the skip logic in the F20-Recovery and F21-Anesthesia transfer forms by correcting the `hideWhenExpression` for specific fields.  This ensures the forms display and hide fields as intended based on user input.
- Corrected the `hideWhenExpression` in the `typeOfMedicationPrescribed` field within the F20-Recovery form to use `includes` correctly.
- Updated the `hideWhenExpression` in the `feeding` field within both the F20-Recovery and F21-Anesthesia transfer forms to include the correct UUID '4c933d68-fda6-4343-b52b-1021c5e5182a'.
Ready for deployment. The changes are straightforward and address …

LIME2-931/LIME2-932: Fix the skip logics in the Anesthesia and Recovery form

---

sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

I verified with UAT DB and the drugs to be removed are no longer present.
- Closes #LIME2-298
------------
**Overview:** This PR updates the changeset ID in the Liquibase configuration file to trigger the re-execution of a script that removes deprecated drugs from the Mosul instance.
- Modified the `liquibase.xml` file to change the ID of the changeset responsible for removing deprecated drugs. This forces Liquibase to re-run the script during the next update.
Ready for deployment. This simple change effectively addresses the issue of the script not running.
| --------- | ------------- |
| Rework   | 1 (100%)      |
| Total …

LIME2-298: Update the changeset id to re-run the script for deleting the deprecated drugs

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F27-Adult_admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F28-Adult_discharge_form.json

- Related to #LIME2-942
------------
**Overview:** This PR removes duplicate "Other" answer concepts from the Adult Admission (F27) and Adult Discharge (F28) forms in the Mosul site configuration.  This corrects redundant entries for "Other symptoms and abnormal clinical/lab findings."
- Removed duplicate "Others" entries with the same concept code as "Other symptoms and abnor. clinical / lab findings" from both F27 and F28 forms.
Ready for deployment. This is a simple, straightforward fix that improves data integrity.
|---|---|
| Churn | 24 (100%) |
| Total Changes | 24 |
<h6>To turn off PR summary, please visit <a …

LIME2-942 Adult forms - delete duplicate other answer concepts

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F08-ITFC_Admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F23-Neonatal_admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F25-Pediatrics_admission_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F26-Pediatrics_discharge_form.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F29-MHPSS_Baseline_v2.json
sites/mosul/configs/openmrs/initializer_config/ampathforms/F53-ATFC_form.json

- Related to #LIME2-952
------------
**Overview:** This PR removes duplicate "Other" concept answer options from several admission and discharge forms and corrects a logic error in a hide expression. It also updates a label in the MHPSS Baseline form and fixes a concept UUID in the ATFC form.
- Removed redundant "Other" concept options from F08, F25, and F26 forms.
- Corrected a hide expression logic error in the F23 form, changing `||` to `&&`.
- Updated a label in the F29 form to remove a formatting issue.
- Fixed a concept UUID in the F53 form, replacing a placeholder name with a valid UUID.
Ready for deployment. This PR improves data quality by …

(fix) LIME2-952 Remove duplicate other concept answer options from forms

---

sites/mosul/configs/openmrs/initializer_config/ampathforms/F13-PNC.json

(fix) LIME2-968 PNC remove incorrect results  viewer workspace
